# -*- coding: utf-8 -*-
"""data analysis - mice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mL9ycfhNWmPKKuEiN0HVZlwaQihkVNh6
"""

import DataIO
import tkinter as tk
from tkinter import filedialog


from plot.fig1_outcome import plot_fig1
from plot.fig1_outcome_short_long import plot_fig1_2
from plot.fig2_trajectory_avg_sess import plot_fig2
from plot.fig3_trajectories import plot_fig3
from plot.fig4_trajectory_avg_sess_superimpose import plot_fig4
from plot.fig5_trajectory_avg_sess_superimpose_short_long import plot_fig5

# from plot.fig6_trajectory_avg_sess_short_long import plot_fig6



# from plot.fig2_complete_trials_percentage import plot_fig2
# from plot.fig3_percentage_epoch import plot_fig3
# from plot.fig4_psychometric_epoch import plot_fig4
# from plot.fig5_stim_isi import plot_fig5
# from plot.fig6_av_sync import plot_fig6
# from plot.fig7_early_iti import plot_fig7
# from plot.fig8_reaction_trial import plot_fig8
# from plot.fig9_reaction_sess import plot_fig9
# from plot.fig10_com import plot_fig10

# session_data_1 = session_data_1
# session_data_2 = session_data_2
# session_data_3 = session_data_3
# session_data_4 = session_data_4


if __name__ == "__main__":


    extract_data = 1
    run_plots = 1

    if extract_data:
        window = tk.Tk()
        window.wm_attributes('-topmost', 1)
        window.withdraw()   # this supress the tk window

        session_data_path = 'C://behavior//session_data'
        file_paths_1 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//LG01', title='Select LG01 Sessions'))
        file_paths_2 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//LG02', title='Select LG02 Sessions'))
        file_paths_3 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//LG05', title='Select LG05 Sessions'))
        file_paths_4 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//FN13', title='Select FN13 Sessions'))
        file_paths_5 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//LG10', title='Select LG10 Sessions'))
        file_paths_6 = list(filedialog.askopenfilenames(parent=window, initialdir=session_data_path+'//LG11', title='Select LG11 Sessions'))

        session_data_1 = DataIO.read_trials('LG01', file_paths_1)
        session_data_2 = DataIO.read_trials('LG02', file_paths_2)
        session_data_3 = DataIO.read_trials('LG05', file_paths_3)
        session_data_4 = DataIO.read_trials('FN13', file_paths_4)
        session_data_5 = DataIO.read_trials('LG10', file_paths_5)
        session_data_6 = DataIO.read_trials('LG11', file_paths_6)


    if run_plots:
        # output_dir_onedrive = 'C:/Users/hpatil39/OneDrive - Georgia Institute of Technology/Najafi_Lab/0_Data_analysis/Behavior/Joystick/test/'
        output_dir_onedrive = 'C:/data analysis/behavior/joystick/figures/'
        output_dir_local = 'C:/data analysis/behavior/joystick/figures/'
        # output_imgs_dir = 'C:/Users/hpatil39/OneDrive - Georgia Institute of Technology/Najafi_Lab/0_Data_analysis/Behavior/Joystick/test/'

        for plotter in [
                plot_fig1,
                plot_fig1_2,
                plot_fig2,
                plot_fig3,
                plot_fig4,
                plot_fig5,
                # plot_fig6,
                # plot_fig7,
                # plot_fig8,
                # plot_fig9,
                # plot_fig10,
                ]:
            for session_data in [
                    session_data_1,
                    session_data_2,
                    session_data_3,
                    session_data_4,
                    session_data_5,
                    session_data_6
                    ]:
                plotter(session_data, output_dir_onedrive, output_dir_local